import { Building2, IdCard, UserRound } from "lucide-react";
import { getProfileData } from "@/features/profile/queries";

const roleLabels = { CLIENT: "Заказчик", MANAGER: "Менеджер", DRIVER: "Водитель", WAREHOUSE: "Склад", ADMIN: "Администратор" } as const;

export async function ProfileView({ user }: { user: Parameters<typeof getProfileData>[0] }) {
  const { company, driver } = await getProfileData(user);
  return <div className="profile-layout"><section className="panel profile-card"><div className="profile-avatar"><UserRound size={23} /></div><span className="eyebrow">ЛИЧНЫЙ ПРОФИЛЬ</span><h2>{user.name}</h2><p>{roleLabels[user.role]} · демо-аккаунт</p><dl className="profile-data"><div><dt>Email</dt><dd>{user.email}</dd></div><div><dt>Телефон</dt><dd>{user.phone || "Не указан"}</dd></div></dl></section>{company ? <section className="panel"><div className="panel-heading"><div className="icon-tile"><Building2 size={18} /></div><div><span className="eyebrow">КОМПАНИЯ</span><h2>{company.displayName}</h2></div></div><dl className="profile-data"><div><dt>Юридическое наименование</dt><dd>{company.legalName || "Не указано"}</dd></div><div><dt>ИНН</dt><dd>{company.inn || "Не указан"}</dd></div><div><dt>Контактный email</dt><dd>{company.email || "Не указан"}</dd></div><div><dt>Телефон</dt><dd>{company.phone || "Не указан"}</dd></div><div><dt>Статус</dt><dd>{company.isActive ? "Активна" : "Отключена"}</dd></div></dl></section> : null}{driver ? <section className="panel"><div className="panel-heading"><div className="icon-tile"><IdCard size={18} /></div><div><span className="eyebrow">ДАННЫЕ ВОДИТЕЛЯ</span><h2>Профиль водителя</h2></div></div><dl className="profile-data"><div><dt>Номер удостоверения</dt><dd>{driver.licenseNumber || "Не указан"}</dd></div><div><dt>Доступность</dt><dd>{driver.isAvailable ? "Свободен для назначений" : "Занят в рейсе"}</dd></div>{driver.notes ? <div><dt>Примечание</dt><dd>{driver.notes}</dd></div> : null}</dl></section> : null}</div>;
}
